### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by jussikinnula** [tajo/react-portal#238]
As a developer, I want to use React 18.

**Comment by aVileBroker** [comment]
I'm having an issue testing portals with react-testing-library. I know ReactDOM.render was deprecated for createRoot, I wonder if something similar happened with ReactDom.renderPortal...

```
Warning: createRoot(): Creating roots directly with document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try using a container element created for your app.

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfReactDOMContainerInDEV (node_modules/react-dom/cjs/react-dom.development.js:29366:7)
      at createRoot (node_modules/react-dom/cjs/react-dom.development.js:29250:3)
      at Object.createRoot$1 [as createRoot] (node_modules/react-dom/cjs/react-dom.development.js:29702:10)
      at Object.<anonymous>.exports.createRoot (node_modules/react-dom/client.js:12:16)
      at createConcurrentRoot (node_modules/@testing-library/react/dist/pure.js:109:27)
      at render (node_modules/@testing-library/react/dist/pure.js:221:12)

    console.error
      Error: Uncaught [NotFoundError: The node to be removed is not a child of this node.]
          at reportException (/Users/oliverbaker/Documents/Git/hs-ui/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at innerInvokeEventListeners (/Users/oliverbaker/Documents/Git/hs-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
          at invokeEventListeners (/Users/oliverbaker/Documents/Git/hs-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
          at HTMLUnknownElementImpl._dispatch (/Users/oliverbaker/Documents/Git/hs-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/oliverbaker/Documents/Git/hs-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
          at HTMLUnknownElement.dispatchEvent (/Users/oliverbaker/Documents/Git/hs-ui/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
          at Object.invokeGuardedCallbackDev (/Users/oliverbaker/Documents/Git/hs-ui/node_modules/react-dom/cjs/react-dom.development.js:4210:16)
          at invokeGuardedCallback (/Users/oliverbaker/Documents/Git/hs-ui/node_modules/react-dom/cjs/react-dom.development.js:4274:31)
          at reportUncaughtErrorInDEV (/Users/oliverbaker/Documents/Git/hs-ui/node_modules/react-dom/cjs/react-dom.development.js:22737:5)
          at captureCommitPhaseError (/Users/oliverbaker/Documents/Git/hs-ui/node_modules/react-dom/cjs/react-dom.development.js:27078:5) DOMException {}

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)

    console.error
      The above error occurred in the <Portal> component:
      
          at Portal (/Users/oliverbaker/Documents/Git/hs-ui/node_modules/react-portal/lib/Portal.js:35:5)
          at Spotlight (/Users/oliverbaker/Documents/Git/hs-ui/src/components/Spotlight/Spotlight.tsx:71:3)
      
      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-dom/cjs/react-dom.development.js:18572:23)
      at update.callback (node_modules/react-dom/cjs/react-dom.development.js:18605:5)
      at callCallback (node_modules/react-dom/cjs/react-dom.development.js:13122:12)
      at commitUpdateQueue (node_modules/react-dom/cjs/react-dom.development.js:13143:9)
      at commitLayoutEffectOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23290:13)
      at commitLayoutMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24578:9)
      at commitLayoutEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24564:7)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:24502:3)

  ● Spotlight › Should match previous snapshot with default props

    NotFoundError: The node to be removed is not a child of this node.



  ● Spotlight › Should match previous snapshot with a targetElement

    Cannot update an unmounted root.
```

**Comment by aVileBroker** [comment]
It seems like it's a problem with rendering the portal in the test with `{ container: document.body }`, as the protal tries to then do the same thing (render into document.body) which React 18 now doesn't like:

https://stackoverflow.com/questions/71792005/react-18-you-are-calling-reactdomclient-createroot-on-a-container-that-has-a
