### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by moroshko** [tajo/react-portal#3]
My app uses `react-portal` to display modals.
I need to generate a static version of my app's HTML for server side rendering.

The problem is that when `react-portal` is loaded in node context (where `document` doesn't exist), it throws the error below.

The error is coming from the `keymaster` dependency, and I wonder whether this dependency is necessary. Looks like it is used only to bind the `ESC` key...

What would be the best way to fix this?

```
$ node
> var portal = require('react-portal')
ReferenceError: document is not defined
    at /Users/mishamoroshko/job-search-panel/node_modules/react-portal/node_modules/keymaster/keymaster.js:267:12
    at Object.<anonymous> (/Users/mishamoroshko/job-search-panel/node_modules/react-portal/node_modules/keymaster/keymaster.js:296:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mishamoroshko/job-search-panel/node_modules/react-portal/portal.js:25:12)
    at Module._compile (module.js:456:26)
```

**Comment by tajo** [comment]
Try `0.4.0` release. I removed the keymaster dep. It should be fine now.

**Comment by moroshko** [comment]
All good now, thanks!
